### ISSUE TITLE
`chmod` builtin is broken

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1146] opened 2019-01-30 10:17 UTC
**Description of problem:**
`-H` and `-P` flags of `chmod` builtin are broken

**Ksh version:**
2017.0.0-devel-2315-gd63b45a7

**How reproducible:**
Always

**Steps to reproduce:**
Try disabled tests of `chmod` builtin (`./src/cmd/ksh93/tests/chmod.sh`)

**Additional info:**
It seems to be broken by e008d7924e6b043beea05e5e341aa9dc14ace079

**Comment by farhaanbukhsh** [comment] 2019-02-08 09:29
Hey I would like to work on this bug, can I set it up on mac os? 
Also what will be the right way to approach it?

**Comment by siteshwar** [comment] 2019-02-08 09:34
@farhaanbukhsh Install meson with `brew install --HEAD meson` on macOS and clone this repo. From root of the repository do `meson build && ninja -C build`. Check the documentation of `chmod` builtin with `chmod --man` and find your way through the code.

**Comment by farhaanbukhsh** [comment] 2019-02-08 10:33
Awesome will do that and ping you here or IRC. Thanks for the help.

**Comment by siteshwar** [comment] 2019-02-21 15:36
@farhaanbukhsh Are you still interested in working on it ?

**Comment by krader1961** [comment] 2019-05-15 03:11
Note that many of the constants in the AST *fts.h* header have different values than on macOS or Linux. For example, `FTS_PHYSICAL` is 0x40 in the AST header and 0x10 in the system header. While 0x40 is `FTS_XDEV` in the system header. So if this used to work before commit e008d79 but after commit 358df55 removed the AST implementation of `fts_open()` and friends it could only be by accident.

**Comment by krader1961** [comment] 2019-05-15 03:54
Also, I just looked and the `chmod -H`  test is incorrect. Which explains why it fails. I haven't yet checked the `chmod -P` case.

**Comment by krader1961** [comment] 2019-05-15 05:03
Hmmm. While the original unit test is flawed the `chmod -RH` implementation is broken. I confirmed the ksh93v- version does the right thing. The problem is that `FTS_COMFOLLOW` in the system header is not the same thing as `FTS_META` in the AST header; despite the comments associated which each symbol implying they are equivalent.

**Comment by krader1961** [comment] 2019-05-15 05:32
To expand on my previous comment. Here is how FTS_META is used in the ksh93v- branch:

https://github.com/att/ast/blob/e770c77e9816e156c6df4a455e71b5f9fff79310/src/lib/libast/misc/fts.c#L604

https://github.com/att/ast/blob/e770c77e9816e156c6df4a455e71b5f9fff79310/src/lib/libast/misc/fts.c#L657-L671

The `FTS_META` symbol is indeed a hack that doesn't interact well with the `fts_*()` family of functions. Specifically, the `fts_set()` function to set the `FTS_FOLLOW` flag on a non top-level symlink that should be followed (or not). Here is an example in the old code that seems to expect no magic from the AST fts code:

https://github.com/att/ast/blob/e770c77e9816e156c6df4a455e71b5f9fff79310/src/lib/libcmd/cksum.c#L619-L625

Note that the `chmod` builtin has no such special-case.

**Comment by krader1961** [comment] 2019-05-17 03:15
The problem is due, in part if not wholly, because the `flags` start out with `FTS_LOGICAL` and when the `-H` flag is handled `FTS_PHYSICAL` is merged into the flag without clearing `FTS_LOGICAL`. Specifying both flags to `fts_open()` is nonsensical. **Oops!** In the AST implementation this mistake is "harmless" because logical traversal is the default. From the AST *fts.h* header:

```
#define FTS_LOGICAL     0               /* logical traversal, follow symlinks   */
```

Whereas on every other platform you have to specify one or the other and if both flags are set the behavior is unspecified.

**Comment by krader1961** [comment] 2019-05-17 05:06
Adding `flags &= ~FTS_LOGICAL;` as the first statement after `case 'H':` in *src/lib/libcmd/chmod.c* fixes one aspect of this issue. Thus confirming my hypothesis.

**Comment by krader1961** [comment] 2019-05-18 05:23
Also, unsurprisingly, the existing implementation of the `chmod -H` ksh93u+ builtin (not just the current git master branch) fails to match the behavior of the external command on BSD based systems like macOS. Without the `-R` flag the presence of `-H` is meaningless and results in an error from the external `chmod` on BSD systems. But when using the ksh93u+ builtin it silently does the wrong thing.

And, of course, the `-H` flag has no meaning on GNU/Linux or SVR4 (e.g., Solaris) systems if you are invoking their external commands rather than the ksh builtin. Which, much like the earlier discussion regarding the behavior of `echo` that depends on the phase of the moon, makes me wonder if the AST ksh team really had a consistent philosophy for such matters.

**Comment by krader1961** [comment] 2019-05-19 21:48
Also, it's not just the `-H`, `-L`, and `-P` flags that are broken. The `-h` flag is also broken on Linux and other OS that don't support a `lchmod()` syscall. The ksh93u+ version fails:

```
chmod: y: cannot change symlink mode [Function not implemented]
```

My fix for the `-H` and `-L` flags since has the side-effect of also fixing the `-h` behavior to match the ksh93u+ version. Which means I now need to figure out the best way to make the unit test portable. 😦

**Comment by krader1961** [comment] 2019-05-19 22:13
Grrr! OpenBSD doesn't have `lchmod()` (whereas macOS and FreeBSD do) but does support the same functionality via `fchmodat(..., AT_SYMLINK_NOFOLLOW)`. I haven't checked if that works on Linux but the Linux man page says it's not supported. But since we'll want to implement a `lchmod()` fallback via a build time feature test it doesn't really matter. Having said that implementing a fallback `lcmod()` will be done as a separate enhancement.

**Closed** 2019-05-23 04:11 UTC
Labels: bug
