### ISSUE TITLE
What should be expected behavior of `--html` builtin option ?

### ISSUE THREAD

**Issue by siteshwar** [att/ast#850] opened 2018-09-09 13:25 UTC
All builtins support `--html` option that outputs a `html` help page on terminal. This is not very helpful. I would expect it to automatically show help page in browser. We need something similar to what `fish` does with `help` command. Comments ?

**Comment by krader1961** [comment] 2019-04-22 03:38
Any reason not to close this as a dup of #507? Once we resolve that issue we will be able to automatically generate a HTML version of each command's documentation. Which can then be used by a hypothetical `help` command such as the `fish` implementation. I also want to see the DocOpt based documentation/flag parsing via `optget()` replaced with the borg standard `getopt_long()` so that we can eliminate the *src/lib/libast/misc/optget.c* module.

**Comment by krader1961** [comment] 2019-08-23 04:16
Once we extricate the documentation from the source and switch to a more modern markup language this becomes moot. So closing as a duplicate of #507.

**Closed by krader1961** 2019-08-23 04:16 UTC
Labels: duplicate, future
