### ISSUE TITLE
Upstream patches from openSUSE

### ISSUE THREAD

**Issue by siteshwar** [att/ast#377] opened 2018-01-20 02:34 UTC
There are some downstream patches in openSUSE [ksh repository](https://build.opensuse.org/package/show/shells/ksh) that we should review and upstream.

**Comment by krader1961** [comment] 2018-01-20 05:35
As usual care needs to be taken when merging downstream fixes. Some, like [cpp.patch](https://build.opensuse.org/package/view_file/shells/ksh/cpp.patch?expand=1), are obviously no longer relevant (in this case because we're no longer using Nmake to build ksh). Others, like [astksh_builtin_poll20120806_001](https://build.opensuse.org/package/view_file/shells/ksh/astksh_builtin_poll20120806_001.diff?expand=1), simply backport an enhancement already present in this project.

The first patch I looked at in that list that looks correct and is still applicable is [ksh93-alias-k](https://build.opensuse.org/package/view_file/shells/ksh/ksh93-alias-k.dif?expand=1). The `alias` and `hash` commands are declarative just like `readonly` or `typeset` AFAICT. The question is what problem (i.e., failure mode) does this change fix? Why hasn't it already been fixed in the upstream project or the Solaris patches I already merged? Especially since it looks like an obviously correct change.

Since I've already merged similar fixes from Solaris we should just merge these as well and hope for the best. It seems unlikely they'll cause more problems than they fix. But, dammit, every single bug fix needs a unit test. I'd write the missing tests if I had some idea what these patches were fixing.

**Comment by krader1961** [comment] 2018-01-20 06:48
The [ksh93-aso](https://build.opensuse.org/package/view_file/shells/ksh/ksh93-aso.dif?expand=1) patch is interesting. It modifies one of the legacy feature detection programs related to the AST "aso" ("atomic scalar operations") code. It appears to be making the feature detection more constrained. I'm going to reject (i.e., ignore) that patch since that particular feature test program is no longer part of the code base. It was removed by commit 108d9a74e. Whether that removal was correct is TBD. Regardless, there shouldn't be anything in the current code focused solely on the `ksh` and related commands that should depend on that feature test. That sort of thing belongs in the implementation of the underlying operating system facilities.

**Comment by krader1961** [comment] 2018-01-20 07:36
This [patch](https://build.opensuse.org/package/view_file/shells/ksh/ksh93-backtick.dif?expand=1) is even more problematic to merge than most of the other patches we've seen since it is a) not obviously correct, and b) lacks any description of what is fixed or regression unit tests. Nonetheless it appears to be a carefully considered change. That change is probably correct. What is not clear is whether is should be applied to this project.

**Comment by siteshwar** [comment] 2018-01-20 09:55
It seems most of these patches were commited by @bitstreamout. @bitstreamout Would it be possible for you to give us context/test cases for these patches ?

**Comment by krader1961** [comment] 2018-01-21 03:02
I'm going to ignore [ksh93-backtick]() because this statement no longer exists:

```
if(!(iop = sftmp(comsub==1?PIPE_BUF:IOBSIZE)))
```

It does exist but the `comsub == 1` ternary is no longer present and the current form just passes `IOBSIZE` to `sftmp()`.

This change is also fairly complex, introducing two new structure members, and we have no idea what it fixes.

**Comment by krader1961** [comment] 2018-01-21 04:10
Fix [ksh93-builtin](https://build.opensuse.org/package/view_file/shells/ksh/ksh93-builtin.dif?expand=1) is interesting in that it appears to build on another fix already merged. It's also interesting because it is cautious about limiting manipulation of the signal mask to Linux. And that doesn't make any sense to me since if that signal mask manipulation is needed it should apply to any UNIX/POSIX system. That is also interesting because it unconditionally references symbols `ECHOKE` and `CMIN` which don't exist on macOS and are only valid for Linux. I'm rejecting this patch because it introduces more unit test failures on macOS.

**Comment by krader1961** [comment] 2018-01-21 04:18
Fix [ksh93-cdpwd](https://build.opensuse.org/package/view_file/shells/ksh/ksh93-cdpwd.dif?expand=1) no longer applies, even by hand, as the `for(dp=dir; ....` statement no longer exists.

**Comment by krader1961** [comment] 2018-01-21 04:24
Fix [ksh93-disable-vfork](https://build.opensuse.org/package/view_file/shells/ksh/ksh93-disable-vfork.dif?expand=1) is particularly interesting in that it disables use of `vfork()`. But since we no longer use that feature test (even in a Meson compatible form) it isn't applicable. But the fact that OpenSuse made that change is intriguing. I'd like to know why they did that.

**Comment by krader1961** [comment] 2018-01-21 04:44
I only merged one change, [ksh93-alias-k](https://build.opensuse.org/package/view_file/shells/ksh/ksh93-alias-k.dif?expand=1). The other fixes were either already merged or had obvious problems due to other changes to the code since the fix was created. At this juncture I think we need to stop trying to apply fixes from other downstream sources. The effort to do so can't be justified. Especially since these changes never include a good (if any) description of the problem being fixed let alone unit tests to prevent regressions.

I would still love to know the specifics of the problem that resulted in https://build.opensuse.org/package/view_file/shells/ksh/ksh93-alias-k.dif?expand=1 so that we can add appropriate unit tests.  @bitstreamout can you provide more context for that change?

**Closed by krader1961** 2018-01-21 04:44 UTC
Labels: bug, cleanup

**Comment by DavidMorano** [comment] 2018-01-21 05:04
> Fix ksh93-disable-vfork is particularly interesting in that it disables use of vfork().

I do not know if my experience is exactly what this change was about, but:
I had to disable the use of |vfork(2)| also and replace it w/ |fork(2)|. I do not have the code in front of me, but the reason was something along the line that there was an intervening |sigprocmask(2)| between the fork and the |exec(2)|.  That messed up the signal mask of the parent, which caused it to hang under some circumstances.

OK, I looked up where that |vfork(2)| was.  It was in the LIBAST file 'misc/spawnvex.c'.
I assume that KSH was calling this (one of these spawn-type subroutines) as its main forking code (for child processes) and this was causing the parent (KSH itself) to occasionally -- but way too often -- to hang.

In general, the use of VFORK is extremely dangerous.  No significant code (other than some kernel calls; moving and closing FDs and setting new process-group IDs and session IDs and the like) should ever be between a VFORK and its corresponding EXECxx. Of course everyone should know -- but always be reminded -- that the use of a VFORK means that the parent and child processes share address space and some other process environment.  Only a few process specific things are different during the time where execution is located between the VFORK and its subsequent EXCExx.

OK, I looked at the 'spawnvex.c' code.  There is a subroutine 'sigcritical()' located between the FORK and the EXECxx.  When this FORK is actually a VFORK (on those systems that still even support a real VFORK), this results in hangs in the parent due to some sort of race or other interference between child and parent. I did not look now, but I assume that inside of that 'sigcritical()' is a secret |sigprocmask(2)| call.  This call affects (apparently) both the parent and child alike since it is located between the VFORK and the subsequent EXECxx. This bug probably also depends on:
+ whether the OS actually supports a real VFORK (and not just a FORK in disguise)
+ the specific OS implementation of VFORK
+ the specific OS implementation of |sigprocmask(2)|

For what it is worth!

**Comment by krader1961** [comment] 2018-01-21 05:23
@DavidMorano, Thank you for that feedback. Your comment suggests that we should unilaterally disable use of `vfork()`. AFACIT we no longer, as a result of switching the build system to Meson, defined `_hdr_vfork` and related symbols. Therefore we no longer use `vfork()` AFAICT. If my assessment is wrong I welcome any change that removes its use or addresses the problems you identified.

**Comment by DavidMorano** [comment] 2018-01-21 06:40
@siteshwar 
> Thank you for that feedback. 
You are very welcome.

> Your comment suggests that we should unilaterally disable use of vfork().
Yes. Either get rid of vfork() (using fork() instead) or have someone investigate refactoring the code in other to remove the use of 'sigcrtical()' from between the vfork() and the subsequent execxx().
For myself, I did not have the time (who does?) to investigate refactoring the code to move that 'sigcritical()' to outside of the crucial code located between the vfork() and the exec(), so instead I just disabled the use of vfork().
I think putting that 'sigcritical()' between the vfork() and the exec() is an asymmetrical anti-pattern that probably should have been avoided in the first place.  Instead some construction like this below (being symmetrical) should have been used:

{
  sigcritical (set-for-child)
  if ((rs = vfork()) == 0) {
    do_child_arrangement
    exec()
    handle_error_condition (minimally)
    exit()
  }
  sigcritcal (reset-back-for-parent)
}
handle_possible_fork_error (looking at variable 'rs' or FIFO output result if that construct is used)

It is the use of VFORK which forces this kind of special care. This is why VFORK is so dangerous (at least for those who do not appreciate that its use is like playing with fire). In short, code that is acceptable for a fork(2) is *not* necessarily acceptable for a vfork(2). The existing code in 'spawnvex.c' treated the use of either fork(2) or vfork(2) as being freely interchangeable. Wrong assumption.

Frankly, when I saw all of those conditional compilation if's in the 'spawnvex.c' code, I threw up my hands and did not feel like playing around with the code any more than was absolutely necessary to get it working properly. That (large) number of conditional compilation blocks makes it hard to fix properly because every single way that it can be conditionally complied needs to be corrected and checked for correctness. Few developers have the time or patience for that sort of hassle -- at least I did not have the time for that.

> Therefore we no longer use vfork() AFAICT.

Good, if this is the case!

IMHO, the 'spawnvex.c' code should never have been so messy in the first place!
I have written several of these spawn-process type subroutines or objects (for OOA/OOD environment) back in the day, and they need to be quite clean to ensure that they function exactly correctly as intended (or else they can be quite difficult to diagnose otherwise). In fact, all code should be written as cleanly as possible.  There are way too many bugs in the world as it is, and developers across the world could spend their time more wisely than revisiting code that should have been totally cleanly written to begin with.

**Comment by krader1961** [comment] 2018-01-21 23:29
> The existing code in 'spawnvex.c' treated the use of either fork(2) or vfork(2) as being freely interchangeable. Wrong assumption.

Yes, this is a good example of "[not even wrong](https://en.wikipedia.org/wiki/Not_even_wrong)" the error is so egregious.

> Frankly, when I saw all of those conditional compilation if's in the 'spawnvex.c' code, I threw up my hands and did not feel like playing around with the code any more than was absolutely necessary to get it working properly.

It's nice to know at least one other person appreciates why I'm aggressively either making features unconditional by removing `#if SHOPT_FEATURE` or removing the conditional code. Where the code does need to be compiled conditionally (e.g., because the platform may or may not provide the needed syscall) the AST code should be refactored so that it is implemented as a clean abstraction rather than embedded spaghetti like.

**Comment by DavidMorano** [comment] 2018-01-22 00:01
@krader1961 
> Where the code does need to be compiled conditionally (e.g., because the platform may or may not provide the needed syscall) the AST code should be refactored so that it is implemented as a clean abstraction rather than embedded spaghetti like.

Totally agreed -- should have been refactored.

I did not know that the code in 'spawnvex.c' was ever going to come up in a discussion, but YES,
IMHO this is a very good example of how *not* to do conditional compilation.

Instead of piece-meal like in this file ('spawnvex.c'), I would do, if forced to, something like:

#if FEATURE

int sub(...) {
  whole-thing ;
  returns ;
}

#else /* FEATURE */

int sub(...) {
  whole-thing ;
  return x ;
}

#endif /* FEATURE */

If finer-grained conditional execution is needed (desired), make subroutines isolating the different code and then put a condition compile-time if around the finer subroutines (each of which wholly coded). Doing this (like in the present case) makes it clearer and more obvious that different implementations (using either vfork or fork) may have differing requirements (or optimizations) about how the code is sequenced inside the critical area between the fork-like call and the exec-like call.

**Comment by DavidMorano** [comment] 2018-01-22 00:31
I do not remember which bistro it was, but sometime within maybe the last few years I saw a change notice (not on regular KSH lists) on some distro (other than openSUSE) where they also replaced vfork w/ fork here in 'spawnvex.c' for KSH.    I do not remember exactly why they needed to to make the change, but it may have also been due to occasional hang conditions as I originally saw. Also, I do not remember them mentioning anything about refactoring the code, just changing vfork to fork. They, likewise, may have been put off by the piece-meal conditional compilation, but just guessing here.
