### ISSUE TITLE
SIGHUP is sent to processes with recycled pids

### ISSUE THREAD

**Issue by siteshwar** [att/ast#116] opened 2017-11-09 19:09 UTC
I have opened this issue to follow up on pull request #1 . More details can be found [here](https://www.mail-archive.com/ast-developers@lists.research.att.com/msg01887.html)

**Comment by krader1961** [comment] 2017-11-09 21:39
Also, PR #1 proposed merging the patch used on Solaris: https://github.com/oracle/solaris-userland/blob/master/components/ksh93/patches/260-22964338.patch. But it wasn't obvious to me that patch does more than paper over a serious bug. If someone can take the time to do a careful analysis of that fix to determine if it is actually fixing, not papering over, the bug that would be appreciated.

**Comment by krader1961** [comment] 2019-08-22 05:17
I can't reproduce this issue using either ksh93u+ or the current version built from git head. I don't see any way for this scenario to occur as documented [here](https://www.mail-archive.com/ast-developers@lists.research.att.com/msg01887.html). If something else is going on such as the ksh process that started the background sleep being unable to run in a timely manner when the background job terminates that might cause this failure. But even that is a stretch since it shouldn't be possible to create an unrelated process using the same PID until the first one, created by the ksh process, has been reaped. And that should keep that ksh process from trying to send SIGHUP to that PID.

I'm going to close this because

a) I can't reproduce the problem,
b) I don't see any practical way for this failure to occur, and
c) The discussion thread has no followup messages,
d) The proposed "fix" is suspect; i.e.,  it's not at all clear it actually fixes the alleged problem rather than papering over it (perhaps by simply changing the timing of events).

It seems likely the environment that results in this failure mode is atypical. For example, `SIGCHLD` is ignored or blocked. However, without more information, in particular a means for others to reproduce this problem, there isn't much we can do.

**Closed by krader1961** 2019-08-22 05:17 UTC
Labels: bug
