### ISSUE TITLE
Race condition when using pipes

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1341] opened 2019-06-25 14:33 UTC
**Description of problem:**
When running ksh scripts, multiple processes are reported running with `$(ps -ef |grep $BNAME|grep -v grep |wc -l)`.  Expect only `1` to be returned but often times see `2+` returned.

**Ksh version:**
2020.0.0-alpha1-192-gf9e984f3-dirty

**How reproducible:**
Always

**Steps to reproduce:**
```
BNAME=`basename $0`
OUT="`ps -ef|grep ${BNAME} | grep -v grep |wc -l`"
if [ ${OUT} -ge "2" ];then
   echo "FAIL"
   exit 1
else
   echo "SUCCESS"
fi
```

**Actual results:**
`FAIL`

**Expected results:**
`SUCCESS`

**Additional info:**
https://bugzilla.redhat.com/show_bug.cgi?id=736195

**Comment by krader1961** [comment] 2019-06-26 04:40
I fail to see the what the problem is. This is not a race condition. It is a consequence of how <code>&grave;...&grave;</code>  interpolation works. AFAICT I would expect this to fail 100% of the time. Changing to `$(...)` interpolation "fixes" the issue. Nonetheless, the nature of the test is wrong which is why I put scare quotes around "fixes".

**Comment by krader1961** [comment] 2019-06-26 04:52
I retract part of my previous comment. This is not a consequence of how <code>&grave;...&grave;</code>  interpolation works. But it is not a race condition. In fact, the current ksh which doesn't use `spawnveg()` fails reliably with three matching processes. The test itself has undefined behavior. Not least of which is due to the grep regexes. Consider what happens if you put the script in a file named *a* and execute `ksh -c a`. Hint: how many lines in the `ps -ef` output contain the letter `a`?

**Comment by krader1961** [comment] 2019-06-26 05:09
I suspect the person who reported this "bug" was trying to detect if a script was being run two or more times simultaneously and was surprised to find that even a single instance caused `ps -ef` to report more than one instance. That is, they were trying to implement a sort of mutual exclusion to ensure no more than one instance of the script was ever running. The approach being used by that person is broken in several ways. The only reliable mechanism is a lock file.

**Comment by kdudka** [comment] 2019-06-26 11:19
As I understand it, the test is broken by design.  It tests something that is not guaranteed to hold.

**Comment by krader1961** [comment] 2019-06-27 05:50
Closing because there is no problem (i.e., bug). The person who originally reported that this behavior did not match their expectation does not understand how command shells handle pipelines. Not to mention understanding how to unambiguously match lines in `ps -ef` output. As @kdudka notes the test is broken because it relies on undefined behavior. Worse, it relies on behavior that cannot be guaranteed given the UNIX process model.

**Closed by krader1961** 2019-06-27 05:50 UTC
Labels: bug, notabug

**Comment by siteshwar** [comment] 2019-06-27 14:49
It's unfortunate that we have been running this test case internally for almost 8 years now and no one noticed it that it's broken.

**Comment by kdudka** [comment] 2019-06-28 08:28
The failing test was reported against bash and zsh 4 years ago and immediately closed as NOTABUG.
