### ISSUE TITLE
`read' does not recognize newline as end-of-input (or another delimiter set via `-d delim')

### ISSUE THREAD

**Issue by jghub** [att/ast#774] opened 2018-08-08 10:20 UTC
seen with Version A 93v-1410-gededd114 under OSX:

(hopefully) minimal example:
```
print -n "gimme input > "
read input
print got "'$input'"
```

instead of expected result (printing out the (newline terminated) input in quotes), the `read` reads beyond the newline indefinitely: it seemingly does not recognise newline as end-of-input as it should. same is happening when using `read -d delim`: the first character of the specified `delim` text is not terminating but just read as part of the input. in this case it is easier to directly see it on the screen that it is happening:
```
print -n "gimme input > "
read -dz input
print got "'$input'"
```
(just enter some text and than a final letter "z": it is simply echoed as part of the provided input instead of ignoring it and returning the rest in variable `input`).

overall it *seems* as if the delimiter to `read` is not honoured at all. that definitely must be some sort of regression (I noted it because one of my interactive scripts stopped working after switching to the above ksh version).

thanks for taking care of ksh!

joerg

**Comment by kusalananda** [comment] 2018-08-08 10:53
Testing the same version of the sources on OpenBSD 6.3, the `read -dz input` work as expected (`z` does not become part of the value stored in `input`).  However, `read input` locks the shell (it starts using 100% CPU) and the shell session has to be killed with the `KILL` signal.

**Comment by jghub** [comment] 2018-08-08 11:02
On 08.08.18 12:53 , Andreas Kusalananda Kähäri wrote:
> Testing the same version of the sources on OpenBSD 6.3, the `read -dz input` work as expected (`z` does not become part of the value stored in `input`).  However, `read input` locks the shell (it starts using 100% CPU) and the shell session has to be killed with the `KILL` signal.
> 

I may add that on OSX I see (sporadic, not quite reproducible) instances, where the never-returning 
`read input' cannot be aborted via SIGINT (ctrl-C) so that indeed it has to be killed, but most of 
the time SIGINT suffices.

**Comment by siteshwar** [comment] 2018-08-08 14:00
This issue is an example why we need to be extra careful while trying to fix warnings produced by static analysis tools. The commit in 1dc56d2151541c8f723240f20faf368a9fee02d9 fixed lint warnings, but introduced a side effect which is very hard to spot during reviews.

@jghub If you are looking for a quick fix, please pull my changes from #775.

**Comment by jghub** [comment] 2018-08-08 14:28
On 08.08.18 16:00 , Siteshwar Vashisht wrote:
> This issue is an example why we need to be extra careful while trying to fix warnings produced by static analysis tools. The commit in 1dc56d2151541c8f723240f20faf368a9fee02d9 fixed lint warnings, but introduced a side effect which is very hard to spot during reviews.
> 
> @jghub If you are looking for a quick fix, please pull my changes from #775.

this is appreciated, thank you. I can confirm that ksh behaviour is back to normal with you quick fix.

otherwise, as a "conservative" guy in these matters, I can only wholeheartedly agree with your above 
remark regarding necessity to be super-careful: while I understand that you (the new maintainers) 
have a hard time with this decades old code-base and its undoubtedly existing idiosyncrasies (and 
sure there are true original bugs inside...), "obsessive" tidy up and elimination of innocuous 
warnings from lint sounds to me like calling for real trouble in terms of serious regressions like 
the present `read` regression via unrecognised side effects.

I mean, unfortunately, not too many people test and report presently issues on github, so the danger 
is substantial that a released version which travels downstream to all the distribution contains 
such a regression.

e.g., I discovered this one only because my scripts all use `#!/usr/bin/env ksh` (and it still took 
weeks until I used an interactive script triggering the bug and another week understanding that it 
is really ksh causing the trouble rather than broken communication to a server which happens at that 
point in the script) while I intentionally put "your" ksh further up the search path than my old 
ks93u. I easily can imagine that I would not have noted it for a long time if the `#!' simply would 
have pointed to /usr/bin/ksh and I would have used the current version only interactively...

it would be really really bad PR for ksh, if that were to happen with a packaged release version in 
all the linux distributions: "ksh is broken. don't touch it" would quite probably be the rapidly 
spreading message...

but to reiterate: I really appreciate your dedication to keeping ksh afloat. it simply is the best 
`sh' successor out there. and I am simply very happy that the new build system is working and ksh 
compiles under OSX (which it did not for quite some time).


>

**Comment by DavidMorano** [comment] 2018-08-08 15:25
@jghub 
> but to reiterate: I really appreciate your dedication to keeping ksh afloat. it simply is the best `sh' successor out there

I agree (KSH is the best POSIX shell); although I recognize, that in its own way, BASH deserves an honorable mention. Not to take anything away from David Korn (rather the opposite), I think that Korn was the primary or major contributor to creating the POSIX standard for the shell in the first place! He was extremely knowledgeable of the current and prior shells (at a very nuanced level) and created the POSIX standard in such a way that balanced various design alternatives which would not overly break existing (prior) shell usage.

> and I am simply very happy that the new build system is working and ksh compiles under OSX (which it did not for quite some time).

I have very sporadically watched KSH on MacOS-X (the standard Apple-delivered version) over the last 15 years or so, but I actually think that there are one or more maintainers somewhere in the bowels of Apple who could use some thanks.  Somehow Apple has updated the KSH on MacOS-X through the years with some observable frequency AND removed some occasional bugs in KSH that showed up as bugs or regressions in the general release of the same KSH version elsewhere. I think only once did I see a regression in the general KSH actually get onto the MacOS-X platform without being spotted and corrected. There may have been other mistakes that got by the Apple maintainers, but there does appear to be some minimal thanks due to one or more Apple maintainers who had been assigned to update KSH though the years on MacOS-X. I just want to give some credit to someone (or more) at Apple where some credit is (IMHO) due. There was someone (through some years and likely continuing) at Apple who seemed to care.

**Comment by jghub** [comment] 2018-08-08 15:40
On 08.08.18 17:25 , David A.D. Morano wrote:
> @jghub
>> but to reiterate: I really appreciate your dedication to keeping ksh afloat. it simply is the best `sh' successor out there
> 
> I agree (KSH is the best POSIX shell); although I recognize, that in its own way, BASH deserves an honorable mention. Not to take anything away from David Korn (rather the opposite), I think that Korn was the primary or major contributor to creating the POSIX standard for the shell in the first place! He was extremely knowledgeable of the current and prior shells (at a very nuanced level) and created the POSIX standard in such a way that balanced various design alternatives which would not overly break existing (prior) shell usage.

+1 to everything said above. as long as the AST mailing list was active and david korn and glen 
fowler were responding there, one could notice that they really cared for ksh and POSIX standard 
compliance and unambiguously well defined behaviour. with bash I am never quite so sure ;). and of 
course ksh is way faster when speed becomes an issue with certain scripts...

> 
>> and I am simply very happy that the new build system is working and ksh compiles under OSX (which it did not for quite some time).
> 
> I have very sporadically watched KSH on MacOS-X (the standard Apple-delivered version) over the last 15 years or so, but I actually think that there are one or more maintainers somewhere in the bowels of Apple who could use some thanks.  Somehow Apple has updated the KSH on MacOS-X through the years with some observable frequency AND removed some occasional bugs in KSH that showed up as bugs or regressions in the general release of the same KSH version elsewhere. I think only once did I see a 

is that the case? I was not aware of this. interesting. I thought they where just using the upstream 
release.

regression in the general KSH actually get onto the MacOS-X platform without being spotted and 
corrected. There may have been other mistakes that got by the Apple maintainers, but there does 
appear to be some minimal thanks due to one or more Apple maintainers who had been assigned to 
update KSH though the years on MacOS-X. I just want to give some credit to someone (or more) at 
Apple where some credit is (IMHO) due. There was someone (through some years and likely continuing) 
at Apple who seemed to care.

if that is the case, than I hope the situation will not change :).

>

**Comment by siteshwar** [comment] 2018-08-09 09:07
> otherwise, as a "conservative" guy in these matters, I can only wholeheartedly agree with your above
remark regarding necessity to be super-careful: while I understand that you (the new maintainers)
have a hard time with this decades old code-base and its undoubtedly existing idiosyncrasies (and
sure there are true original bugs inside...), "obsessive" tidy up and elimination of innocuous
warnings from lint sounds to me like calling for real trouble in terms of serious regressions like
the present `read` regression via unrecognised side effects.

It is more important to fix these bugs as soon as someone hits them. Also, we need to do better job at testing. But I take your point about not trying to blindly fix every lint warning. We need to be extra careful about statements that have side effects.

> I mean, unfortunately, not too many people test and report presently issues on github, so the danger
is substantial that a released version which travels downstream to all the distribution contains
such a regression.

I am hoping that more people will adopt our changes. It is close to impossible to maintain full `ksh93u+` codebase that contained all AT&T specific tools like nmake, iffe etc. It keeps breaking even when there is no change to `ksh` itself. For e.g. it may break due to [update in glibc](https://bugzilla.redhat.com/show_bug.cgi?id=1477082). I have even seen it breaking on changing optimization level of compilers.

> it would be really really bad PR for ksh, if that were to happen with a packaged release version in
all the linux distributions: "ksh is broken. don't touch it" would quite probably be the rapidly
spreading message...

It has been this way before I started working on ksh. That's why I try to keep changes in RHEL/Fedora to minimal and only fix critical bugs. Unfortunately this also means some of the real bugs will never be solved unless we make some radical changes in upstream.

**Comment by krader1961** [comment] 2018-08-12 05:58
@siteshwar wrote

> ... some of the real bugs will never be solved unless we make some radical changes in upstream.

That understates the problem.  Very few people who care about ksh remaining a viable POSIX shell will contribute improvements unless the barrier to entry is considerably lower than it was when the project was moved to Github. And that means removing every single bit of code that is not directly relevant to `ksh`.

**Closed** 2018-08-13 05:10 UTC
Labels: bug
