### ISSUE TITLE
'meson' does not clean some(all?) of its `/tmp/tmp*` folders --

### ISSUE THREAD

**Issue by aabatpurdue** [att/ast#868] opened 2018-09-13 10:04 UTC
**Description of problem:**
When you run `meson build`,`meson` leaves trash lying around `/tmp`.

**Ksh version:**
September 3rd clone.

**How reproducible:**
Always

**Steps to reproduce:**
1. `meson build`
2.
3.

**Actual results:**
A number of `/tmp/tmp*` folders.

**Expected results:**
The folders removed.

**Additional info:**

**Comment by siteshwar** [comment] 2018-09-13 12:35
If you are running tests, directories for the tests that fail are preserved for debugging.

**Comment by krader1961** [comment] 2018-09-13 21:11
As siteshwar pointed out we deliberately leave temp directories for tests that fail. That's to aid in debugging the failure. But those should all have a `ksh.` prefix not `tmp`. And, of course, tests aren't run during `meson build`. Too, as far as I know, none of the config time feature tests create any files in */tmp*.

@aabatpurdue What are in those directories?

**Comment by aabatpurdue** [comment] 2018-09-13 23:49
@krader1961 The directory names are `/tmp/tmp*` not `/tmp/ksh*` and they do appear after a `meson build` run.  They are all names generated with random trailer characters (`mktemp -d tmp`? or python's equivalent function).

They do clutter `/tmp` though and, unless you are always aware of them, they will be forgotten until such time in the future they are observed again.  Their numbers increase with every run of `meson`.

My two cents would be to make a single outer directory and put the dirs/files that I am seeing as sub-dirs/files there. The outer dir name could also include such dumb things as date+time   so you could actually see the progression.  I don't know if it's possible but the inner subdir could be explicitely identified also.

**Comment by krader1961** [comment] 2018-09-14 00:01
@aabatpurdue You didn't answer my question. What are in those directories?

As we've already said we do not expect temp files to be created, let alone left around, after the build. No one else is seeing this behavior. So unless you can provide more details we're not going to be able to resolve this.

**Comment by krader1961** [comment] 2018-09-14 00:08
You didn't say what platform you're using but looking at your Github profile I'm guessing it's Cygwin or WSL. I build ksh and run it's unit tests every day on both platforms, as well as three Linux and three BSD platforms. I'm not seeing any */tmp/tmp...* directories on any of them as a result of building ksh or running its unit tests. So there may be something unusual about your environment.

**Comment by aabatpurdue** [comment] 2018-09-14 01:10
Actually the answer I gave is correct, `/tmp/tmp*/`.  One example is `/tmp/tmpd2nvxx8h/`.  
See the attached  ![tmpdirs](https://user-images.githubusercontent.com/21324717/45523811-25642700-b799-11e8-8968-06dcf0b64e59.png).  I have been building a port to MSYS2 but have been using Cygwin also.  Just looked at the Cygwin `/tmp`  and there are 117 of these subdir types there.  The attachment is a snip of that `/tmp`.

**Comment by krader1961** [comment] 2018-09-14 02:12
@aabatpurdue No one is arguing that you aren't seeing those directories be created. But no one else is seeing that behavior. And you still haven't answered my question. **What is in those directories?** And what is in the files in those directories? Also, what is the output `meson --version` and `ninja --version`?

P.S., Screen shots are generally not helpful except when you need to show a visual artifact. And for that using something like asciinema is generally a better choice.

**Comment by aabatpurdue** [comment] 2018-09-14 02:46
OK - more like  [tmp6hvga54i-ascii.cast.txt](https://github.com/att/ast/files/2381663/tmp6hvga54i-ascii.cast.txt)?  Boy, `asciinema play` is as slow as molasses in January at the top of the world.

`meson --version`  <-- Cygwin
`0.47.1`

`ninja --version`  <-- Cygwin
`1.8.2`

**Comment by krader1961** [comment] 2018-09-14 02:57
@aabatpurdue I did not mean for you to use asciinema for this issue. You should try to find a way to enable SSH so that you can login to your system using a terminal from which you can cut/paste text into issues like this one.

Fortunately the raw asciinema file you uploaded makes it clear the file is an artifact of statements like this one in the top level *meson.build*:

```
wchar_t_size = cc.sizeof('wchar_t', prefix: '#include <wchar.h>')
```

This project has absolutely no control over how Meson executes such statements. You'll need to open an issue against the Meson project.

Since I'm not seeing those feature test artifacts on Cygwin there is something unusual about your system. Perhaps your */tmp/* dir is reached via a [NTFS junction point](https://en.wikipedia.org/wiki/NTFS_junction_point) or something similar which is making it impossible for Meson to remove those directories. Or perhaps a process is still running that has one of the files open. On UNIX that doesn't cause a problem but on Windows it makes it impossible to delete the file.

I'm going to close this since the problem is not under the control of this project.

**Closed by krader1961** 2018-09-14 02:57 UTC
Labels: question
