### ISSUE TITLE
"print -v" outputs incorrect binary value for integer variable

### ISSUE THREAD

**Issue by sneyx123** [att/ast#1291] opened 2019-04-25 05:29 UTC
**Description of problem:**
Builtin "print" with option "-v" prints value of variable by name reference.
In case of a "integer" attributed variable the builtin "print" output the raw binary value ...

**Ksh version:**
# print -v .sh.version
Version AJM 93u+ 2012-08-01

**How reproducible:**
Interactive via controlling tty or as script.

**Steps to reproduce:**
1. integer V2=65
2. print -v V2
3.

**Actual results:**
�@

**Expected results:**
65

**Additional info:**

**Comment by krader1961** [comment] 2019-04-25 05:49
Why do you expect a literal `65` to be output? When exploring this type of problem it is a good idea to pipe the output through something like `xxd` or `od -tx1z`.

I'll grant you I can't explain the output I am seeing since it is a 16 byte value whose content has no obvious relationship to the actual value assigned to the integer var. Be it `1`, `255`, `256`, etc. Only zero outputs all zero bytes as I would expect. I'm wondering if the value is being treated as a long double (i.e., floating point) value when written.

What brought this to your attention?

Note that ksh93u+, ksh93v-, and ksh from the current master branch of this project all exhibit the same behavior.

**Comment by krader1961** [comment] 2019-04-25 05:53
I'm testing this on macOS with 64 bit ints and seeing this behavior:

```
$ src/cmd/ksh93/ksh -c 'integer V2=0; print -nv V2' | god -tx1z
0000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
0000020
$ src/cmd/ksh93/ksh -c 'integer V2=1; print -nv V2' | god -tx1z
0000000 00 00 00 00 00 00 00 80 ff 3f 00 00 00 00 00 00  >........?......<
0000020
```

You should always mention the OS/distro and hardware you are using when reporting a problem of this nature.

**Comment by krader1961** [comment] 2019-04-25 06:02
Also, there are some unit tests of `print -v` and `printf %B` behavior but it isn't obvious they are confirming correct behavior rather than just affirming the existing behavior. In no small part because it is unclear what `printf %B` really means. And @fpmurphy documents this feature [here](https://blog.fpmurphy.com/2017/08/manipulating-binary-data-using-the-korn-shell.html). However, I haven't actually read that blog post with the goal of understanding what is being said so I have no idea if it is accurate. I will say that the idea of a POSIX shell like ksh being used to manipulate binary data makes me scream "run away".

**Comment by sneyx123** [comment] 2019-04-25 06:06
It should be literal because more complex types are also literal:
# typeset -a A1=(111 aaa 333)
# print -v A1
(
        111
        aaa
        333
)
# Above ISO layer 6 we should have abstraction from vendors etc...

**Comment by krader1961** [comment] 2019-04-25 06:07
> It should be literal because more complex types are also literal:

That is not what the documentation implies:

> A  %B  option  causes each of the arguments to be treated as variable names and the binary value of variable will be printed.

**Comment by sneyx123** [comment] 2019-04-25 06:09
So "-v" is literal and abstract syntax and "-f '%B'" is binary and concrete syntax.

**Comment by sneyx123** [comment] 2019-04-25 06:11
print -v V2|xxd
00000000: 0000 0000 0000 0082 0540 0000 0000 0000  .........@......
00000010: 0a                                       .

**Comment by krader1961** [comment] 2019-04-25 06:13
> So "-v" is literal and abstract syntax and "-f '%B'" is binary and concrete syntax.

No. Again, from the documentation:

> The -v option treats each arg as a  variable name  and  writes  the  value in the printf %B format.

I see the exact same output with `print -v V2` and `printf '%B' V2`. Are you seeing something else?

**Comment by sneyx123** [comment] 2019-04-25 06:15
# print -nv V2|xxd
00000000: 0000 0000 0000 0082 0540 0000 0000 0000  .........@......
# print -f '%B' V2|xxd
00000000: 0000 0000 0000 0082 0540 0000 0000 0000  .........@......

**Comment by krader1961** [comment] 2019-04-25 06:16
I agree this feature is broken. But it's been broken for at least seven years since that was when ksh93u+ was release. It's probably been broken longer than that. What might help is if you could explain what caused this bug to come to your attention.

**Comment by sneyx123** [comment] 2019-04-25 06:17
A option to enable/disable bug for bug would be fine ...

**Comment by krader1961** [comment] 2019-04-25 06:19
> A option to enable/disable bug for bug would be fine ...

I don't understand. Are you saying you don't see this bug in ksh93t+ or an earlier release?

**Comment by sneyx123** [comment] 2019-04-25 06:23
It was always a bug until a amendment will allow it per option to be enabled or disabled.

**Comment by krader1961** [comment] 2019-04-25 06:29
> It was always a bug until a amendment will allow it per option to be enabled or disabled.

I recognize that English isn't your native language but I can't make any sense of that statement. Before we talk about adding an option to enable or disable the current behavior we should first agree on what is the correct behavior. Then we can talk about about whether the behavior should be changed with or without introducing an option in order to maintain backward compatibility.

**Comment by sneyx123** [comment] 2019-04-25 06:30
I can't see a systematic approach here:
# typeset -C OBJ1
# integer OBJ1.V3=65
# print -v OBJ1
(
        typeset -l -i V3=65
)
# print -v OBJ1.V3
�@

**Comment by krader1961** [comment] 2019-04-25 06:36
> I can't see a systematic approach here:

That's because the people who wrote this code didn't think carefully about the design for this feature. This is implied in the documentation of the `%#B` variant for compound vars. You seem to be confusing the behavior of `print -v` when the var is a scalar (e.g., an integer) and when it is a compound var. I think the different behavior of those two cases is itself a bug. Albeit a design bug. But that is a different issue from printing the binary form of a scalar integer var whose output has no obvious relationship to the integer.

**Comment by sneyx123** [comment] 2019-04-25 06:38
# typeset OBJ1.S1=$' \t\n'
# print -v OBJ1
(
        S1=$' \t\n'
        typeset -l -i V3=65
)
# print -v OBJ1.S1 | xxd
00000000: 2009 0a0a                                 ...

That means it is nor only "raw" for intergers ...

**Comment by sneyx123** [comment] 2019-04-25 06:50
There is always the idea that you *can* "print" in a syntax notation and format that can be used for "eval" as argument. The output and input notation must be systematic bidirecitonal. Thats for all kinds of variable essential.

**Comment by krader1961** [comment] 2019-04-25 06:56
> There is always the idea that you can "print" in a syntax notation and format that can be used for "eval" as argument. The output and input notation must be systematic bidirecitonal.

That is nonsense. Where is it documented that ksh `print -v` outputs its arguments in a form that can be fed into `eval` to reproduce the original vars? I agree that something like Python's `repr` output is useful I don't see what that has to do with `print -v` or the equivalent `printf '%B'`.

**Comment by krader1961** [comment] 2019-04-25 07:02
Again, you have missed my point, and the seemingly explicit documentation, that `printf '%B'` outputs the binary value of the var. This feature is completely unrelated to your expectation of something like Python's `repr` output which is a syntactically valid representation of the object even if it is a simple scalar like an int.

**Comment by krader1961** [comment] 2019-04-25 21:44
Here is the bug:

https://github.com/att/ast/blob/788b926e3da19edf72c59060f0c5ad55d1ac8236/src/cmd/ksh93/bltins/print.c#L546-L548

Hint #1: See issue #855

Hint #2: `#define NV_DOUBLE (NV_INTEGER | NV_ZFILL)`

Hint #3: The value of `np->nvflag` is 0xA which is `NV_INTEGER | NV_UTOL`. The latter symbol is also aliased here: `#define NV_LONG (NV_UTOL)`. So 0xA can also be expressed as `NV_INTEGER | NV_LONG`.

**Comment by krader1961** [comment] 2019-04-25 21:47
@sneyx123 FWIW, if you really want a var displayed in a fashion that is syntactically valid you should use `typeset -p` not `print -v`.

**Closed** 2019-04-25 23:56 UTC
Labels: bug

**Comment by sneyx123** [comment] 2019-04-26 04:10
For complex (huge) values (e.g. compound, indexed array and associative array -- and any nested cobinations) the output wound be more readable in a pretty printed (intended and multiline) form-- like "print -v" does. Also it is nice to have a separation of "name", "type" and "value" ... e.g.: 
   print -f "%s\n" "$(typeset +p "${VAR_VARNAM}")=$(print -v "${VAR_VARNAM}")"

**Comment by sneyx123** [comment] 2019-04-26 04:18
If you try to pretty print the output of "typeset -p" in the a intended and multiline form you will end up in implementation of a parser ... that will end up in a parser written in ksh to parse ksh syntax ...

**Comment by sneyx123** [comment] 2019-04-26 04:31
Example:
# typeset -A MY_MATRIX=([automatic]=([monkey]=a [2]=bb [4]=ccc) [magic]=([1]=x [2]=yy [3]=zzz))
# typeset -p MY_MATRIX
typeset -A MY_MATRIX=([automatic]=([2]=bb [4]=ccc [monkey]=a) [magic]=([1]=x [2]=yy [3]=zzz) )
# print -v MY_MATRIX
(
        [automatic]=(
                [2]=bb
                [4]=ccc
                [monkey]=a
        )
        [magic]=(
                [1]=x
                [2]=yy
                [3]=zzz
        )
)

**Comment by krader1961** [comment] 2019-04-26 04:31
@sneyx123 You are welcome to open an issue requesting the feature you desire. I don't know why the AT&T AST team made `print -v` do something different when given a compound or array var versus a simple scalar var. But the document makes it quite clear that the binary output of something like `integer x=1; print -v x` is the primary purpose of this feature. That example produces incorrect output, and has done so for at least seven years (the ksh93u+ release), until I merged my fix a few hours ago. So I am willing to discuss removing support for binary output and changing the meaning of `print -v` to produce symbolic output in the fashion you describe even if the var is a simple scalar (whether string, int, float, etc.) rather than a compound var. Not because I like your proposal but because I find the current difference in the output based on whether it is a simple scalar or not to be a [bogosity](https://www.urbandictionary.com/define.php?term=bogosity). So if nothing else I'd like to eliminate that behavior.

**Comment by krader1961** [comment] 2019-04-26 04:35
@sneyx123 Please take a few minutes to read about how to use Markdown to embed literal code in your comments: https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by sneyx123** [comment] 2019-04-26 04:45
I was to much problem oriented -- of course I will read it.

**Comment by krader1961** [comment] 2019-04-26 04:52
Also, it probably makes more sense for the output of `typeset -p` to be in a "pretty print" format than it does to modify what `print -v` outputs. Especially since the documentation makes it clear that the primary purpose of `typeset -p` is to write to stdout

> the name, attributes and values for the given vnames are  written  on standard  output in a form that can be used as shell input.

There isn't any reason that output should not also be easy for a human to read.

**Comment by dannyweldon** [comment] 2019-04-26 08:59
> There isn't any reason that output should not also be easy for a human to read.

Having one variable output per line makes it very easy to parse and extract bits out if needed.  I think it would be better to add an additional option to enable pretty printing or perhaps use `-pp` or `-p -p` ?
