### ISSUE TITLE
DEL in empty terminal or at end of line makes ksh exit

### ISSUE THREAD

**Issue by brdjns** [att/ast#1039] opened 2018-12-01 11:06 UTC
**Description of problem**
Pushing `DEL` at the end of a line of characters or in an empty terminal causes `ksh` to exit, closing
the terminal window.
 
 **Ksh version**
 `ksh-20120801` 
 
 **How reproducible**
 Always.
 
 **Steps to reproduce:**
* Create a new user and switch to it.
 ```
 useradd test -s /bin/ksh 
 su - test
```

* Type a line of characters; don’t push `RET`. 
* Place the cursor at the end of the line.
* Push `DEL`.

 **Actual results:**
`ksh` exits and the terminal window closes.
 
 **Expected results**
 Typing `DEL` should have no effect when there are no more characters to delete. 
 
 **Additional info**
System is Debian GNU/Linux "Stretch".  Bug is present in the distro
version, and also present in builds from master in the present repository. 

The only way I’ve found to remedy this is to configure `xterm` to  
send a `127` code instead of `177` when pushing `DEL`, but this makes it delete
backwards, essentially duplicating the functionality of `BKSPC`.

This behaviour is consistent whether or not `kbd_trap()` is set in `.kshrc`.
This is not a long term solution and hampers productivity.

**Comment by siteshwar** [comment] 2018-12-01 16:58
I could not reproduce this bug. I have tried these configurations:

- `ksh-20120801` and latest development version on `konsole` terminal on Fedora 28.
- `ksh-93u+20120801-3.1` on Debian (in docker) running under `konsole`.
- `ksh-20120801` and latest development version on `xterm` on Fedora 28.

@brdjns Does `ksh` crash or just exits ? How does `valgrind` output look like if it crashes ?

**Comment by krader1961** [comment] 2018-12-01 23:48
Works for me; i.e., I can't reproduce your problem. What does `stty -a` output? In particular does `^?` appear in the "cchars" section? Perhaps you've assigned <del> to to the tty quit function which causes a SIGQUIT to be sent to the shell. If that doesn't explain the behavior you're seeing please start a shell and run `echo $$`. Then in a different window `strace -o /tmp/ksh.trace -f -ttt -p $pid` where `$pid` is the value from the preceding echo.

**Comment by brdjns** [comment] 2018-12-02 08:04
> Works for me; i.e., I can't reproduce your problem. What does `stty -a` output? In particular does `^?` appear in the "cchars" section? Perhaps you've assigned DEL to to the tty quit function which causes a SIGQUIT to be sent to the shell. If that doesn't explain the behavior you're seeing please start a shell and run `echo $$`. Then in a different window `strace -o /tmp/ksh.trace -f -ttt -p $pid` where `$pid` is the value from the preceding echo.

Output of `ssty -a`:
```
speed 38400 baud; rows 88; columns 159; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```
Output of `strace -o /tmp/ksh.trace -f -ttt -p 15080`
```
15080 1543737173.661228 select(1, [0], NULL, NULL, NULL) = 1 (in [0])
15080 1543737179.671173 recvfrom(0, 0x7ffc8d942c40, 80, MSG_PEEK, NULL, NULL) = -1 ENOTSOCK (Socket operation on non-socket)
15080 1543737179.671508 read(0, "\33[3~", 80) = 4
15080 1543737179.671894 ioctl(2, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
15080 1543737179.672195 ioctl(2, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
15080 1543737179.672369 ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
15080 1543737179.672500 getpid()        = 15080
15080 1543737179.672603 ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
15080 1543737179.672701 setpgid(0, 15080) = -1 EPERM (Operation not permitted)
15080 1543737179.672833 write(2, "\n", 1) = 1
15080 1543737179.673023 fstat(3, {st_mode=S_IFREG|0600, st_size=17818, ...}) = 0
15080 1543737179.674700 lseek(3, 0, SEEK_CUR) = 17774
15080 1543737179.674812 fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 6), ...}) = 0
15080 1543737179.674917 fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 6), ...}) = 0
15080 1543737179.675039 exit_group(0)   = ?
15080 1543737179.675609 +++ exited with 0 +++
```

**Comment by krader1961** [comment] 2018-12-02 23:05
> The only way I’ve found to remedy this is to configure xterm to send a 127 code instead of 177 when pushing DEL

Your DEL key was not sending octal 177. From the strace we can see it is sending `\33[3~` which is a common variant that is typically known as termcap attr `dc` and terminfo attr `kdch1`. And it's not clear what you mean when you say you've reconfigured your terminal to send `127` since that octal value is the letter `W`. And decimal 127 is the same as octal 177; they're both the del char.

The rest of the strace is what we would expect when the shell receives the EOF char; typically [ctrl-D]. However, that is ignored unless it is the first character at a fresh prompt. And in any event the trace shows that [ctrl-D] wasn't received.

Stock ksh doesn't bind anything to the `\33[3~` sequence. Do you have a keybd trap installed? What does `trap` output?

@brdjns The way you phrased the "steps to reproduce" is curious. Does the problem not occur if you press DEL at a fresh prompt? And why do I need to "Place the cursor at the end of the line" after typing  a line of characters. At that point the cursor should already be at the end of the line. I shouldn't need to press [right-arrow] or [ctrl-E] or anything else to move the cursor to the end of the line because it should already be in that location.

**Comment by siteshwar** [comment] 2018-12-21 23:43
Closing due to lack of information. Please reopen if you still have this issue.

**Closed** 2018-12-21 23:43 UTC
Labels: needs-more-info
