### ISSUE TITLE
Tab completion chokes on ~/some

### ISSUE THREAD

**Issue by siteshwar** [att/ast#682] opened 2018-07-13 15:10 UTC
@kusalananda reports at https://github.com/att/ksh/issues/3:

Version AJM 93u+ 2012-08-01 running on OpenBSD 6.1 (but have been observed elsewhere).

Tab completion does not work in Vi mode (only) for completing a subdirectory name in one's home directory, if tab is pressed after the fourth character of the directory name:

$ cd ~/loca

Pressing tab at this point starts moving the cursor to the left, over the entered text, eventually leaving the command line reading

cd /home/

This does not occur if the tab completion is initiated after the third or fifth entered character.

This also affects completion of file names.

If ~username is used, then tab completion fails if pressing tab when the length of the username plus the entered length of the name of the file/dir is four characters:

ls ~kk/dm

**Comment by kusalananda** [comment] 2018-07-13 15:34
@siteshwar  Thanks for moving it, sorry for my confusion.

**Comment by siteshwar** [comment] 2018-07-13 15:43
@kusalananda No worries. fwiw https://github.com/att/ksh/ has been deleted to avoid any confusions in future.

**Comment by kusalananda** [comment] 2018-08-08 07:00
This bug seems to have been resolved in the development version.  The version I tried is `Version A 93v-1400-g3d8a9fe4`.

I'm not closing the issue since I don't know whether you'd like to do some other tests for this first (or write regression tests).

**Closed** 2018-09-05 23:35 UTC
Labels: bug
