### ISSUE TITLE
test glob and friends succeed only with LC_ALL='C' or unset

### ISSUE THREAD

**Issue by catull** [att/ast#268] opened 2017-12-26 21:17 UTC
The 3 `glob` tests fail on Fedora and macOS when `LC_ALL` is set to anything other than 'C', e.g. 'en_US.UTF-8'.

The tests succeed if the variable is not set, or set as `LC_ALL='C'`.
It is considered a bug.

**Comment by krader1961** [comment] 2017-12-26 21:37
Some tests, by their very nature, require a specific locale. It's not clear from your problem description if you think the problem is that the test framework doesn't override any LC_&ast;/LANG env vars the user might have set. Or if the problem is that those tests fail if the locale isn't `C`.

**Comment by catull** [comment] 2017-12-26 21:58
I am quoting your own words, in https://github.com/att/ast/issues/255#issuecomment-353765919 you state:
> Thanks for bringing this to our attention, @catull. This is an example of something that might have been okay more than a decade ago but is no longer valid.

> I'm going to reopen this because unit tests should be immune to the user's values for locale env vars. I have LANG=en_US.UTF-8 in my environment but do not have a LC_ALL var. Simply setting LC_ALL in my environment should not affect unit test behavior. Unit tests are, by definition, supposed to be immune to the preferences of the user running them.

In issue #255 it was about a strange case of working in macOS but not in Fedora.
Here it is about the test which only works with LC_ALL='C' or unset.

How can this be fixed ?

I can see a couple of ways.

A) The test case could be split into 3 different ones: `glob`, `glob-C` and `glob-en_US.UTF-8`.
     In each one of them, LC_ALL is set accordingly - except for in `glob` it is specifically unset.
B) The set is run with LC_ALL='C' because that is the pattern I see most "compatible"

In both scenarios, the original value of LC_ALL is saved away and restored after the test exits.

By "most compatible" I mean, pretty much everywhere in the code base LC_ALL is used explicitly as `env LC_ALL='C' some_command ....`

Back in the '80s there was no UTF-8 in use on Unix systems.
UTF-8 became the default encoding format for Solaris and Linux only at the beginning of the century, perhaps a few years before the turn of the century.

Perhaps there are other ways to better deal with the situation.
The easiest way would be option B) with pre-saving and restoring the env variable LC_ALL.

**Comment by catull** [comment] 2017-12-26 22:17
[Lines 24-31 of src/cmd/ksh93/tests/shtests](https://github.com/att/ast/blob/master/src/cmd/ksh93/tests/shtests#L24-L31) state:
```
    The default environment settings are:]
    {
        [+unset LANG]
        [+unset LC_ALL]
        [+LC_NUMERIC=C?\b.\b radix point assumed by all test scripts.]
        [+VMALLOC_OPTIONS=abort?\bvmalloc\b(1) arena checking enabled
            with \babort(2)\b on error.]
    }
```

I think the case is clear now.

**Comment by krader1961** [comment] 2017-12-27 01:22
> In both scenarios, the original value of LC_ALL is saved away and restored after the test exits.

That should not be necessary. Environment vars are inherited. If the test framework changes an env var such as `LC_ALL` that will not affect the environment of the person running the test.

Note that running without a specific locale being set by the test framework means it will use whatever locale is in effect when the tests start running. That is, it will use the value of `LANG` and the other `LC_`&ast; vars. That is not good. While we might want to provide a way to explicitly test using an unusual locale the default should always be a hermetic test environment that is not influenced by user preferences such as the current value of `LANG` or `LC_ALL`.

Note that if the test environment unsets `LANG` and `LC_ALL` that should be equivalent to `LC_ALL=C` assuming no other `LC_`&ast; vars are set. Which is not a safe assumption. We should ensure that all locale vars are either not set or set to known values as as `C` and `en_US.UTF-8`. Long term this should be extended to other locales that don't share the assumptions implicit in those American centric locales.

**Comment by krader1961** [comment] 2018-05-01 03:46
The `glob` tests are currently passing on all platforms. Granted we don't currently test locale `en_US.UTF-8` but when I modify *src/cmd/ksh93/meson.build* by substituting that locale for `C.UTF-8` the test still passes. It's likely my recent changes to have the tests run by a consistent framework and without being influenced by the locale env vars of whomever is running the test has fixed this. So I'm closing this since it appears to no longer be an issue.

**Closed by krader1961** 2018-05-01 03:46 UTC
Labels: bug
