### ISSUE TITLE
strdup() usage without error checking

### ISSUE THREAD

**Issue by floppym** [att/ast#1397] opened 2019-09-05 16:12 UTC
I noticed `strdup()` is used all over the place, with no checks for `NULL` result as would occur when the system is running low on memory (`errno == ENOMEM`).

Am I missing something, or is this an actual bug?

**Comment by krader1961** [comment] 2019-09-05 18:42
There are also lots of malloc()/calloc()/realloc() calls which don't check the return value. The real question is why are there any places in the ksh (not libast) code which does explicitly test that those functions do not return a NULL pointer. Every single instance I've examined simply returns an error indicator, usually NULL, to the caller **and the caller never checks that the call failed.** Once in a while you'll find that the caller does and returns an error but it's caller in turn does not check for failure. So all that happens is the dereferencing of the NULL pointer just happens later. There might be places in the code which do actually try to recover, or at least fail in some manner other than SIGSEGV, but I haven't encountered any.

Consider that `strdup()` is never called to duplicate multi-megabyte strings. It's almost always going to be less than 1 KiB. If such an allocation fails there really isn't much you can do other than write an error message, maybe do some cleanup (e.g., close file descriptors, network connections, etc.), then die. So I have no objection to establishing a consistent pattern for such situations. But the current scheme of writing code like this is completely pointless:

```
char *do_something(char *str) {
    char *new_str = strdup(str);
    if (!new_str) return NULL;
    *new_str = 'X'
    return new_str;
}

void whatever() {
    char *str = do_something("hello");
    if (!strcmp(str, "Xello")) {
        // whatever
    }
}
```

**Comment by krader1961** [comment] 2019-09-07 02:45
Here is an example of the anti-pattern I spoke about in my previous comment:

https://github.com/att/ast/blob/a9d4bb0064df247b20f604626b5b58698079bd4d/src/cmd/ksh93/sh/init.c#L1148-L1149

https://github.com/att/ast/blob/a9d4bb0064df247b20f604626b5b58698079bd4d/src/cmd/ksh93/sh/init.c#L1585-L1589

Notice that the sole caller or `nv_init()` simply assumes a non-NULL pointer will be returned. The shell will blow up soon when it tries to use `shp->init_context` is used. That check for `calloc()` failing is pointless and actually counter-productive.

**Comment by krader1961** [comment] 2019-09-15 06:06
This is effectively a duplicate of #853 that I opened a year ago. The problem is even more profound than discussed here. See https://github.com/att/ast/issues/853#issuecomment-427545542 for one such example.

OOM (out of memory) and related failures are handled inconsistently, and mostly nonsensically, in the current code. Given how ksh is typically used there is zero justification for trying to handle `malloc()` and related failures.

**Comment by krader1961** [comment] 2019-09-29 02:58
I am mildly surprised this issue hasn't sparked more discussion. FWIW, I have already removed some pointless `if (!ptr) return NULL;` like statements in the past couple of years. I think I'll spend a half hour tonight seeing if there are any others beyond the one in `nv_init()` and remove those as well. If anyone can actually point to an example in the code where such checks are actually meaningful I'd love a pointer to that case. I still stand by my statement that such checks are harmful because they provide the illusion of guarding against an OOM situation.

**Comment by floppym** [comment] 2019-09-29 03:02
I agree that OOM should probably just be fatal in most cases. Letting the code deref the null pointers feels dirty to me, but I suppose it gets the job done.

**Comment by krader1961** [comment] 2019-09-29 03:09
@floppym Given that we currently have wrappers in place for the malloc family of functions it would be trivial to do something in those wrapper functions if the real malloc function failed; e.g., print a message to stderr before calling `abort()`. Do you (or anyone else) have an opinion on whether that is preferable to simply letting a future NULL dereference cause the failure?

**Comment by krader1961** [comment] 2019-09-29 03:20
Here's another example where the explicit check is pointless:

https://github.com/att/ast/blob/2828fd98a2db434fd8826265f56955a1102ea2e3/src/cmd/ksh93/bltins/enum.c#L292-L296

Notice that the `error()` function itself is almost certain to dynamically allocate memory. Too, in this case the failure occurred while executing a shell `enum` command. Which means that the shell will then deal with a failed command and likely execute the next shell statement. All of which is also certain to dynamically allocate memory. In other words, explicitly checking for a failed `calloc()` call in this instance is counterproductive.

**Comment by floppym** [comment] 2019-09-29 03:23
I do think a message like "Cannot allocate memory" (as returned by `strerror(ENOMEM)`) might be more useful to the user than a generic "killed by signal SIGSEGV" message. The latter usually indicates a bug in the program, rather than a system problem.

Of course on Linux, the program is more likely to be killed by the kernel OOM process with SIGKILL rather than getting ENOMEM from malloc() due to over-allocation. But that will at least show up in the kernel log anyway.

**Comment by krader1961** [comment] 2019-09-29 03:28
Reopening the issue, briefly, so we don't forget to alter the malloc wrappers if that is deemed preferable to just letting the NULL dereference kill the program.

**Comment by krader1961** [comment] 2019-09-29 03:40
Here is another example why these explicit OOM checks are harmful rather than helpful. From function `sh_timeradd()`:

https://github.com/att/ast/blob/2828fd98a2db434fd8826265f56955a1102ea2e3/src/cmd/ksh93/sh/timers.c#L172-L176

If we OOM the shell simply, and silently, doesn't set a timer (probably for a `read -t $timeout`). Gosh, what could possibly go wrong with that approach?

**Comment by krader1961** [comment] 2019-09-29 03:42
And the same idiocy a few lines later:

https://github.com/att/ast/blob/2828fd98a2db434fd8826265f56955a1102ea2e3/src/cmd/ksh93/sh/timers.c#L188-L192

**Comment by krader1961** [comment] 2019-09-29 03:47
The small number of places that explicitly check if the malloc failed compared to the number which are not checked appears to be a case of [Cargo cult programming](https://en.wikipedia.org/wiki/Cargo_cult_programming).

**Comment by krader1961** [comment] 2019-09-29 04:04
You can certainly make a, weak, argument that a general purpose library, like libast, should explicitly check if malloc has failed and return an appropriate error value. But I can't see any cases of that nature in the libast source that make sense. For example, in `spawnvex_open()`:

https://github.com/att/ast/blob/2828fd98a2db434fd8826265f56955a1102ea2e3/src/lib/libast/misc/spawnvex.c#L126-L137

There is only one call site which checks if it returns a non-NULL value and that check is completely bogus:

https://github.com/att/ast/blob/2828fd98a2db434fd8826265f56955a1102ea2e3/src/cmd/ksh93/sh/macro.c#L2440-L2443

If the `calloc()` call made by `spawnvex_open()` fails then we don't set the `shp->vex` structure member. **W.T.F.!**

**Comment by dannyweldon** [comment] 2019-09-29 04:17
It would still be useful for an interactive shell not to die if it can't allocate memory but just emit an error message and return to the prompt, though implementing that may not be easy.

**Comment by krader1961** [comment] 2019-09-29 04:30
@dannyweldon Not only would that not be easy it is effectively impossible. Every state transition in a ksh shell instance needs to dynamically allocate memory. In your hypothetical situation the expansion of `$PS1` will be problematic because that requires malloc functions to succeed. There is literally no way for these attempts to recover from an OOM condition to result in a usable shell instance other than by happenstance. That is, accidentally rather than by design.

**Comment by krader1961** [comment] 2019-09-29 05:47
Closing this again because I have pushed a commit that eliminates the obvious tests of malloc failures in the ksh code. I'm leaving issue #853 open because I believe all of those malloc failure checks also need to be eliminated. If for no other reason than the vast majority of libast malloc calls do not explicitly test if that call failed.

**Closed by krader1961** 2019-09-29 05:47 UTC
Labels: duplicate, question
