### ISSUE TITLE
cannot enable job control from command line (option -m ineffective)

### ISSUE THREAD

**Issue by g-raud** [att/ast#517] opened 2018-05-08 17:14 UTC
The following log shows that when `-m` (or `-o monitor`) is passed on the command line, the asynchronous command is stopped by SIGTSTP; it implies that is it not in a separate process group thus that job control is not enabled.  The expected behaviour is the same as when `set -m` is given as the first command as the manpage indicates:

```sh
$ ksh -m -c 'sleep 3& sleep 2'
^Z
[1]+  Stopped                 ksh -m -c 'sleep 3& sleep 2'
$ ps -Ho pid,state,command
  PID S COMMAND
26229 S -bash
11443 T   ksh -m -c sleep 3& sleep 2
11450 T     ksh -m -c sleep 3& sleep 2
13265 R   ps -Ho pid,state,command
$ fg
ksh -m -c 'sleep 3& sleep 2'
$ ksh -c 'set -m; sleep 3& sleep 2'
^Z
[1]+  Stopped                 ksh -m -c 'sleep 3& sleep 2'
$ ps -Ho pid,state,command
  PID S COMMAND
26229 S -bash
14295 T   ksh -c set -m; sleep 3& sleep 2
14296 S     ksh -c set -m; sleep 3& sleep 2
14330 R   ps -Ho pid,state,command
$ ps -Ho pid,state,command
  PID S COMMAND
26229 S -bash
14295 T   ksh -c set -m; sleep 3& sleep 2
14296 Z     [ksh] <defunct>
14379 R   ps -Ho pid,state,command
$ fg
ksh -c 'set -m; sleep 3& sleep 2'
```

This bug is present in pdksh and mksh and has already been reported to the mksh mailing list: see https://www.mail-archive.com/miros-mksh@mirbsd.org/msg00872.html.  bash and dash do not have this bug (at least not in recent versions).

**Comment by siteshwar** [comment] 2018-07-02 14:25
Closing as not a bug.

**Closed by siteshwar** 2018-07-02 14:25 UTC
Labels: needs-more-info

**Comment by g-raud** [comment] 2018-07-12 11:30
> You are getting the same result in both cases indeed. However the result you
> are getting is the wrong one: the fact that the job "sleep 3&" is defunct shows
> that it has not been stopped hence that job control is not enabled.

I was wrong, you are wright: you do not have this bug.  However the
version in Debian still does.

**Comment by g-raud** [comment] 2018-07-12 12:11
This bug is fixed in the current git repo (2018/07) and it has been reported to the Debian BTS (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903638).
